name: Car Seller Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  application-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Directory Permissions
        run: |
          find . -type d -exec chmod 2750 {} + || true
          find . -type f -exec chmod 640 {} + || true
          find storage -type d -exec chmod 2770 {} + || true
          find storage -type f -exec chmod 660 {} + || true
          find bootstrap/cache -type d -exec chmod 2770 {} + || true
          find bootstrap/cache -type f -exec chmod 660 {} + || true
          ls -la .

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set Application Encryption Key
        run: php artisan key:generate --ansi

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Install node dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Execute tests via PHPUnit/Pest
        run: php artisan test
